# ~/.profile: executed by Bourne-compatible login shells.

export PS1="[\[\e[31m\]\D{%F %T}\e[0m\]->\e[1;33m\]\u\e[0m\]@\e[36m\]\w\[\e[0m\]]$"

if [ "$BASH" ]; then
  if [ -f ~/.bashrc ]; then
    . ~/.bashrc
  fi
fi

ulimit -c unlimited
