# ~/.profile: executed by Bourne-compatible login shells.

export PS1="\[\e[0;31m\]\D{%F %T}|\[\e[1;33m\]\u|\[\e[36m\]\w$"
export HOMEBREW_NO_AUTO_UPDATE=true
#PS1="\[\e[0;31m\] \u@\h \W\$ \[\e[0m\] "

[ -f /usr/local/etc/profile.d/autojump.sh ] && . /usr/local/etc/profile.d/autojump.sh

if [ "$BASH" ]; then
    if [ -f ~/.bashrc ]; then
        . ~/.bashrc
    fi
fi

ulimit -c unlimited
export PATH="/usr/local/opt/sphinx-doc/bin:$PATH"
export PATH="/usr/local/opt/gettext/bin:$PATH"
