# ~/.profile: executed by Bourne-compatible login shells.

TZ='Asia/Shanghai'; export TZ

if [ "$BASH" ]; then
  if [ -f ~/.bashrc ]; then
    . ~/.bashrc
  fi
fi

JAVA_HOME=/opt/soft/jdk1.7.0_79
PATH=$JAVA_HOME/bin:$PATH
export JAVA_HOME 
export PATH
mesg n
