# ~/.profile: executed by Bourne-compatible login shells.

TZ='Asia/Shanghai'; export TZ

if [ "$BASH" ]; then
  if [ -f ~/.bashrc ]; then
    . ~/.bashrc
  fi
fi

JAVA_HOME=/opt/soft/jdk1.7.0_79
PATH=$JAVA_HOME/bin:$PATH
export JAVA_HOME
export PATH

ulimit -c unlimited
export JAVA_HOME 
export PATH
mesg n

# Setting PATH for Python 2.7
# The orginal version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/2.7/bin:${PATH}"
export PATH
