#!/bin/bash

[[ -s `brew --prefix`/etc/autojump.sh ]] && . `brew --prefix`/etc/autojump.sh

export PATH=/usr/local/bin:/usr/local/sbin:$PATH
export MANPATH=$MANPATH:/usr/local/opt/erlang/lib/erlang/man
#export PATH="/usr/local/Cellar/php56/5.6.0/bin:$PATH"
#export PATH="/usr/local/Cellar/mysql55/5.5.30/bin:$PATH"
#export PATH="/usr/local/nginx/sbin:$PATH"
#export PATH="/Users/Seapeak/tencent/tool/apache-maven-3.3.3/bin:$PATH"

export JAVA_HOME="/Library/Java/JavaVirtualMachines/jdk1.7.0_51.jdk/Contents/Home/"
export M2_HOME="/Users/Seapeak/tencent/tool/apache-maven-3.3.3/"

#添加git的自动完成命令功能
if [ -f ~/.git-completion.bash ]; then
    source ~/.git-completion.bash
fi

[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm" # Load RVM function

if [ -f /usr/local/bin/virtualenvwrapper.sh ]; then
    source /usr/local/bin/virtualenvwrapper.sh
fi

if [ -f ~/.aliasrc ]; then
    source ~/.aliasrc
fi

ulimit -c unlimited
export PATH="/Users/xuhaifeng/settings/mysys/bin:$PATH"
PATH=$PATH:/opt/pkg_uninstaller

bind '"\e[A": history-search-backward'
bind '"\e[B": history-search-forward'


